config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "pages#home"
get '/about' ,to: "pages#about"
resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
 validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
def hello
render plain: "hello gokul bhai"
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

 def new
  @todo = Todo.new
 end
 def create
  @todo = Todo.new(todo_params)
  if @todo.save
    flash[:notice] = "Todo was created successfully"
    redirect_to todo_path(@todo)
  else
    render 'new'
  end    
 end    
 def show
  @todo= Todo.find(params[:id])
 end
 def edit
  @todo = Todo.find(params[:id])
 end
 def update
  @todo = Todo.find(params[:id])
  if @todo.update(todo_params)
    flash[:notice] = "Todo was updated successfully"
    redirect_to todo_path(@todo)
  else
    render 'edit'
  end 
 end
 def destroy
  @todo = Todo.find(params[:id])
  @todo.destroy
  flash[:notice] = "Todo was deleted successfully"
  redirect_to todos_path
end
 def index
  @todos = Todo.all
 end
 private

  def todo_params
   params.require(:todo).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xyz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<% flash.each do |name, msg| %>
	<ul>
	<li><%= msg %></li>
	</ul>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2> This is about page <h2>

app/views/pages/home.html.erb
<h1>Hello World!</h1>

app/views/todos/edit.html.erb
<h1>Editing te a new Todo</h1>
<% if @todo.errors.any? %>
<h2>The following errors prevented the todo from being saved</h2>
<ul>
<% @todo.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
<%= form_for @todo do |f| %>

<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/todos/index.html.erb
<h1>Listing all Todos</h1>

<p>
  <%= link_to "Create a Todo", new_todo_path %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @todos.each do |todo| %>
    <tr>
      <td><%= todo.name %></td>
      <td><%= todo.description %></td>
      <td><%= link_to "Edit", edit_todo_path(todo) %></td>
      <td><%= link_to "Show", todo_path(todo) %></td>
	<td><%= link_to 'delete', todo_path(todo), method: :delete, data: { confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h1>Create a new Todo</h1>
<% if @todo.errors.any? %>
<h2>The following errors prevented the todo from being saved</h2>
<ul>
<% @todo.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
<%= form_for @todo do |f| %>

<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/todos/show.html.erb
<h1>Showing a todo</h1>

<p>
name: <%= @todo.name %>
</p>
<p>
description: <%= @todo.description %>
</p>

<%= link_to "Edit this todo", edit_todo_path(@todo) %> |
<%= link_to "Back to todos listing", todos_path %>